@WebApi_HostAddress = http://localhost:5245

GET {{WebApi_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{WebApi_HostAddress}}/route/ad18c57a67f067609ed8dbf3070c4290
Accept: application/json

###
// POST request corresponding to the example at
// https://docs.nextbillion.ai/optimization/route-optimization-api/tutorials/basic-route-optimization

POST {{WebApi_HostAddress}}/route
Content-Type: application/json
Accept: application/json

<@ ./SampleInputs/basic-route-optimization.json

###
// Scenario 1: 10 jobs on June 10, 2025, 1 vehicle, 1 depot, 11 locations, 1 lunch break, start and end at depot, no skills, no shipments

POST {{WebApi_HostAddress}}/route
Content-Type: application/json
Accept: application/json

<@ ./SampleInputs/scenario-01.json

###
// Scenario 2: 10 jobs on June 10, 2025, 1 vehicle, 1 depot, 11 locations, 1 lunch break, start and end at depot, no skills, no shipments

POST {{WebApi_HostAddress}}/route
Content-Type: application/json
Accept: application/json

<@ ./SampleInputs/scenario-02.json

###
